# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    paths-ignore:
      - "doc/**"
      - "README.md"
      - "**.md"
      - "LICENSE**"
  pull_request:
    paths-ignore:
      - "doc/**"
      - "README.md"
      - "**.md"
      - "LICENSE**"

jobs:
  build:
    strategy:
      matrix:
        arch: [x86_64]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Zig
        uses: actions/setup-zig@v1
        #with:
        #  version: 0.12.0
      - name: build
        run: zig build